#!/bin/bash
# discard-manifest.sh — Category-level compaction discard manifest (T-2366, arc-012 S4)
#
# Slice S4 of T-2158 (continuous-run). When the agent self-compacts at a
# context-budget boundary, the handover that fires (pre-compact.sh / checkpoint.sh
# → handover.sh, unified under D-028) leaves behind a machine-readable record of
# WHAT was discarded, so the operator can review post-hoc.
#
# Category-level fidelity is sufficient and is all that is achievable: the model
# self-compacts internally, so a token-level before/after diff is impossible
# (T-2158 S6 Q4). This script reports counts and the working-set file list mined
# from the current session transcript — the categories that compaction sheds.
#
# Usage:
#   discard-manifest.sh [SESSION_ID]
#     SESSION_ID  optional; defaults to $SESSION_ID env or a timestamp stamp.
#
# Honours env: PROJECT_ROOT, CONTEXT_DIR, HANDOVER_DIR (else derived).
# Prints the manifest path on stdout. Never fails the caller — on any error it
# emits a minimal valid-YAML manifest with source: unavailable and exits 0.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
FRAMEWORK_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$FRAMEWORK_ROOT/lib/paths.sh" 2>/dev/null

HANDOVER_DIR="${HANDOVER_DIR:-$CONTEXT_DIR/handovers}"
SESSION_ID="${1:-${SESSION_ID:-S-$(date +%Y-%m%d-%H%M)}}"
MANIFEST_FILE="$HANDOVER_DIR/$SESSION_ID.discard-manifest.yaml"
TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

mkdir -p "$HANDOVER_DIR" 2>/dev/null

# Derive the JSONL transcript dir (T-2380 encoding + T-2400 worktree resolution):
# Claude Code keys the projects dir on the session's LAUNCH cwd — in a worktree
# that is the MAIN repo, not PROJECT_ROOT. So search ALL candidate dirs
# (PROJECT_ROOT-keyed AND the primary-worktree/main-repo dir, via the shared
# fw_claude_project_dirs resolver) and return the dir holding the globally-newest
# transcript. Falls back to the PROJECT_ROOT-keyed dir name when none is found
# (keeps the downstream "no transcript" branch working).
_jsonl_dir() {
    local newest
    newest=$(
        while IFS= read -r d; do
            find "$d" -maxdepth 1 -name "*.jsonl" -type f ! -name "agent-*" -print0 2>/dev/null
        done < <(fw_claude_project_dirs) | xargs -r -0 ls -t 2>/dev/null | head -1
    )
    if [ -n "$newest" ]; then
        dirname "$newest"
    else
        echo "$HOME/.claude/projects/$(fw_claude_project_dir_name "${PROJECT_ROOT:-$(pwd)}")"
    fi
}
# FW_DISCARD_JSONL_DIR is a test seam: point at a fixture dir of *.jsonl to
# exercise the transcript-parse branch deterministically (see tests).
JSONL_DIR="${FW_DISCARD_JSONL_DIR:-$(_jsonl_dir)}"

# Session-metrics fallback (turns) when no transcript is reachable.
METRICS_FILE="$CONTEXT_DIR/working/.session-metrics.yaml"
FALLBACK_TURNS=""
if [ -f "$METRICS_FILE" ]; then
    FALLBACK_TURNS=$(grep '^session_turns:' "$METRICS_FILE" 2>/dev/null | awk '{print $2}')
fi

# Single streaming Python pass over the newest non-agent transcript. Bounded to
# one file (the current session) for the <500ms budget — never globs all sessions.
python3 - "$JSONL_DIR" "$MANIFEST_FILE" "$SESSION_ID" "$TIMESTAMP" "${FALLBACK_TURNS:-}" << 'PYEOF'
import sys, json, os, glob

jsonl_dir, manifest_file, session_id, timestamp, fallback_turns = sys.argv[1:6]

def write_manifest(source, tool_results, turns, files, note):
    lines = [
        "# Discard manifest — category-level compaction discards (T-2366, arc-012 S4)",
        "# Generated by agents/handover/discard-manifest.sh. Category-level fidelity:",
        "# the model self-compacts so a token-level diff is impossible (T-2158 S6 Q4).",
        f"session_id: {session_id}",
        f"generated: {timestamp}",
        f"source: {source}",
        f"tool_results_compressed_count: {tool_results}",
        f"turns_summarized_count: {turns}",
        "files_dropped_from_working_set:",
    ]
    if files:
        for p in files:
            # YAML-safe single-quote (double any embedded quote).
            safe = str(p).replace("'", "''")
            lines.append(f"  - '{safe}'")
    else:
        lines[-1] = "files_dropped_from_working_set: []"
    lines.append(f"note: \"{note}\"")
    with open(manifest_file, "w") as fh:
        fh.write("\n".join(lines) + "\n")

CATEGORY_NOTE = ("category-level estimate; counts the tool-results, model turns, and "
                 "working-set files at risk of compaction. Token-level fidelity is not "
                 "achievable (model self-compacts).")

try:
    pattern = os.path.join(jsonl_dir, "*.jsonl")
    cands = [f for f in glob.glob(pattern)
             if not os.path.basename(f).startswith("agent-")]
    if not cands:
        raise FileNotFoundError("no session transcript")
    # Newest by mtime = current session.
    transcript = max(cands, key=os.path.getmtime)

    tool_results = 0
    turns = 0
    files = []
    seen = set()
    edit_tools = {"Read", "Edit", "Write", "NotebookEdit", "MultiEdit"}

    with open(transcript) as fh:
        for line in fh:
            try:
                e = json.loads(line)
            except Exception:
                continue
            msg = e.get("message")
            if not isinstance(msg, dict):
                continue
            role = msg.get("role")
            content = msg.get("content")
            # Assistant turns with real model output count as summarised turns.
            if role == "assistant" and msg.get("model", "") and not msg.get("model", "").startswith("<"):
                turns += 1
            # Scan content blocks for tool_result (compaction targets) and
            # file-touching tool_use (working-set members).
            if isinstance(content, list):
                for block in content:
                    if not isinstance(block, dict):
                        continue
                    btype = block.get("type")
                    if btype == "tool_result":
                        tool_results += 1
                    elif btype == "tool_use" and block.get("name") in edit_tools:
                        fp = (block.get("input") or {}).get("file_path")
                        if fp and fp not in seen:
                            seen.add(fp)
                            files.append(fp)

    files.sort()
    write_manifest("transcript", tool_results, turns, files, CATEGORY_NOTE)
except Exception:
    # Graceful degradation: never fail the handover. Fall back to session-metrics
    # turn count when the transcript is unreachable (e.g. fresh worktree).
    turns = fallback_turns if fallback_turns.strip() else "0"
    src = "metrics-fallback" if fallback_turns.strip() else "unavailable"
    note = ("transcript unreachable; turns from .session-metrics.yaml, "
            "no working-set enumeration available." if src == "metrics-fallback"
            else "no transcript and no session metrics; manifest is a structural placeholder.")
    write_manifest(src, 0, turns, [], note)
PYEOF

echo "$MANIFEST_FILE"
