#!/usr/bin/env python3
"""embed-fonts.py — fetch the designer's web fonts and emit a self-contained
`<style>` block with the woff2 faces inlined as base64 data URIs.

T-176 (arc: designer-authoring-surface). The designer previously linked Google
Fonts (fonts.googleapis.com / gstatic), so the "single-file" artifact AEF
vendors made a live network call at load and lost fidelity offline. This
generator produces the inline replacement so `src/aef-workflow-designer.html`
is truly zero-network.

Reproducible: re-run to re-fetch and re-embed after a weight/family change,
instead of hand-editing base64. Deterministic given the same upstream faces
(Google serves stable versioned gstatic URLs; output ordering is sorted).

Families / weights embedded (must match the CSS `--mono` / `--sans` stacks):
    JetBrains Mono : 400, 500, 600      (--mono)
    Outfit         : 400, 500, 600, 700 (--sans)

By default all unicode-range subsets Google returns are embedded (full
fidelity). Pass --latin-only to embed just the latin + latin-ext subsets
(smaller; drops cyrillic/greek/vietnamese to system fallback).

Usage:
    python3 scripts/embed-fonts.py            # -> prints the <style> block to stdout
    python3 scripts/embed-fonts.py -o out.css # -> writes the block to a file
    python3 scripts/embed-fonts.py --latin-only

Requires network to fonts.googleapis.com / fonts.gstatic.com at BUILD time only.
The produced artifact needs no network at RUN time.
"""
import argparse
import base64
import re
import sys
import urllib.request

CSS2_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=JetBrains+Mono:wght@400;500;600"
    "&family=Outfit:wght@400;500;600;700"
    "&display=swap"
)

# A modern desktop-Chrome UA makes the css2 endpoint serve woff2 (the default
# urllib UA gets legacy TTF). woff2 is ~40% smaller and universally supported.
_UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
       "Chrome/124.0.0.0 Safari/537.36")

# Subset comment Google emits right before each @font-face, e.g. `/* latin */`.
_SUBSET_RE = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*")
_FACE_RE = re.compile(r"@font-face\s*\{(.*?)\}", re.DOTALL)
_URL_RE = re.compile(r"url\((https://[^)]+\.woff2)\)")
_LATIN_SUBSETS = {"latin", "latin-ext"}


def _fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": _UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read()
    return data if binary else data.decode("utf-8")


def build_style_block(latin_only=False):
    css = _fetch(CSS2_URL)
    # Split into (subset_label, face_body) pairs by walking the subset comments.
    faces = []
    pos = 0
    for m in _SUBSET_RE.finditer(css):
        subset = m.group(1)
        face_m = _FACE_RE.search(css, m.end())
        if not face_m:
            continue
        faces.append((subset, face_m.group(1)))
        pos = face_m.end()
    if not faces:
        raise SystemExit("FAIL: no @font-face blocks parsed — did the css2 format change?")

    out_faces = []
    total = 0
    for subset, body in faces:
        if latin_only and subset not in _LATIN_SUBSETS:
            continue
        url_m = _URL_RE.search(body)
        if not url_m:
            continue
        woff2 = _fetch(url_m.group(1), binary=True)
        total += len(woff2)
        b64 = base64.b64encode(woff2).decode("ascii")
        new_body = _URL_RE.sub(
            "url(data:font/woff2;base64,%s)" % b64, body, count=1
        ).strip()
        out_faces.append("/* %s */\n@font-face {\n%s\n}" % (subset, new_body))

    # NOTE: deliberately do NOT print the source css2 URL here — the embedded
    # output must be grep-clean of external font hosts (T-176 AC / verification).
    # The source URL lives in this generator (CSS2_URL) instead.
    header = ("  <!-- T-176: web fonts embedded as base64 woff2 (offline / zero-network).\n"
              "       Generated by scripts/embed-fonts.py — do not hand-edit; re-run to refresh.\n"
              "       JetBrains Mono 400/500/600 + Outfit 400/500/600/700, latin + latin-ext. -->")
    block = "%s\n  <style>\n%s\n  </style>" % (header, "\n".join(out_faces))
    return block, total, len(out_faces)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--output", help="write the <style> block here (default: stdout)")
    ap.add_argument("--latin-only", action="store_true",
                    help="embed only latin + latin-ext subsets (smaller)")
    args = ap.parse_args()

    block, total, n = build_style_block(latin_only=args.latin_only)
    sys.stderr.write("embedded %d face(s), %.0f KB of woff2 (base64 ≈ %.0f KB)\n"
                     % (n, total / 1024, total * 4 / 3 / 1024))
    if args.output:
        with open(args.output, "w") as f:
            f.write(block + "\n")
        sys.stderr.write("wrote %s\n" % args.output)
    else:
        print(block)


if __name__ == "__main__":
    main()
