#!/usr/bin/env python3
"""
antigravity_steps.py — Antigravity Workflow Step Engine for AEF

Provides step handlers and operational automation for Antigravity-native
AEF agents, including self-provisioning, subagent scoping, and health audits.

Functions:
  - provision_step(project_root) -> dict
  - audit_step(project_root) -> dict
  - subagent_dispatch_step(project_root, task_id, role, prompt, model) -> dict
  - render_artifact_step(project_root, name, title, content) -> str
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

def provision_step(project_root: Path) -> Dict[str, Any]:
    """Provisions Antigravity configuration in the target project."""
    provision_script = project_root / ".agentic-framework" / "agents" / "sessions" / "antigravity" / "provision.sh"
    if not provision_script.is_file():
        # Fallback to local script directory
        provision_script = Path(__file__).resolve().parent.parent / "agents" / "sessions" / "antigravity" / "provision.sh"

    if not provision_script.is_file():
        return {"ok": False, "error": f"Provisioning script not found at {provision_script}"}

    proc = subprocess.run(
        [str(provision_script), str(project_root)],
        capture_output=True,
        text=True
    )
    return {
        "ok": proc.returncode == 0,
        "stdout": proc.stdout.strip(),
        "stderr": proc.stderr.strip(),
        "exit_code": proc.returncode
    }

def audit_step(project_root: Path) -> Dict[str, Any]:
    """Audits the Antigravity integration health in the target project."""
    agents_dir = project_root / ".agents"
    hooks_file = agents_dir / "hooks.json"
    mcp_file = agents_dir / "mcp_config.json"
    skill_file = agents_dir / "skills" / "aef-assistant" / "SKILL.md"
    symlink_fw = agents_dir / ".agentic-framework"
    agents_md = project_root / "AGENTS.md"
    gemini_md = project_root / "GEMINI.md"

    checks = {
        "agents_dir": agents_dir.is_dir(),
        "hooks_json": hooks_file.is_file(),
        "mcp_config_json": mcp_file.is_file(),
        "skill_aef_assistant": skill_file.is_file(),
        "symlink_framework": symlink_fw.exists() or symlink_fw.is_symlink(),
        "agents_md": agents_md.exists(),
        "gemini_md": gemini_md.exists(),
    }

    # Exercise hooks
    hook_probe = project_root / ".agentic-framework" / "lib" / "doctor-hook-exercise.py"
    hook_status = "untested"
    if hook_probe.is_file() and hooks_file.is_file():
        env = dict(os.environ, SETTINGS_FILE=str(hooks_file), PROJECT_ROOT=str(project_root))
        proc = subprocess.run([sys.executable, str(hook_probe)], capture_output=True, text=True, env=env)
        hook_status = proc.stdout.strip()

    all_passed = all(checks.values())
    return {
        "ok": all_passed,
        "checks": checks,
        "hook_exercise": hook_status,
        "summary": "All Antigravity components healthy" if all_passed else "One or more Antigravity components missing"
    }

def subagent_dispatch_step(
    project_root: Path,
    task_id: str,
    role: str,
    prompt: str,
    model: str = "inherit",
    workspace_mode: str = "inherit"
) -> Dict[str, Any]:
    """Prepares structured specifications for invoking an Antigravity subagent."""
    # Ensure task lock and context exists
    context_dir = project_root / ".context" / "working"
    context_dir.mkdir(parents=True, exist_ok=True)

    enriched_prompt = f"""[AEF TASK CONTEXT]
Active Task: {task_id}
Working Directory: {project_root}
Governance: P-002 Active (All changes must be attributed to {task_id})

[TASK PROMPT]
{prompt}
"""

    subagent_spec = {
        "TypeName": "self",
        "Role": role,
        "Prompt": enriched_prompt,
        "Model": model,
        "Workspace": workspace_mode,
        "task_id": task_id
    }
    return {
        "ok": True,
        "subagent_spec": subagent_spec,
        "instructions": "Pass subagent_spec to the invoke_subagent tool call."
    }

def render_artifact_step(
    project_root: Path,
    artifact_name: str,
    title: str,
    content: str,
    task_id: Optional[str] = None
) -> str:
    """Formats standardized markdown artifact adhering to AGY guidelines."""
    task_header = f"> **AEF Task**: [`{task_id}`](file://{project_root}/.tasks/active/{task_id}.md)\n\n" if task_id else ""
    return f"""# {title}

{task_header}{content}

---
*Generated by AEF Antigravity Step Engine*
"""

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Antigravity Step Engine CLI")
    parser.add_argument("action", choices=["provision", "audit", "subagent-spec"])
    parser.add_argument("--project", default=os.getcwd(), help="Target project root")
    parser.add_argument("--task", default="", help="Active task ID")
    parser.add_argument("--role", default="Worker", help="Subagent role")
    parser.add_argument("--prompt", default="", help="Subagent prompt")
    
    args = parser.parse_args()
    proj = Path(args.project).resolve()
    
    if args.action == "provision":
        res = provision_step(proj)
        print(json.dumps(res, indent=2))
    elif args.action == "audit":
        res = audit_step(proj)
        print(json.dumps(res, indent=2))
    elif args.action == "subagent-spec":
        res = subagent_dispatch_step(proj, args.task, args.role, args.prompt)
        print(json.dumps(res, indent=2))
