"""govd_sandbox — OS sandbox profile emit / install / drift (arc-013 / T-2433, design §7a).

The cage's static floor — uid demotion (S5), RO governance substrate (S4), egress
pinned to the proxy (S3) — is derived from ONE sovereign-authored source
(`policy/sandbox-profile.yaml`) plus the repo layout, and rendered to artefacts the
host can check *before* anything is installed:

  - aef-agent.service            systemd unit: User=, ProtectSystem=strict, ReadWritePaths=
                                 (working tree) with ReadOnlyPaths= (substrate) nested inside.
                                 Checked by `systemd-analyze verify`.
  - aef-agent-egress.nft         nftables OUTPUT-hook ruleset keyed on the agent uid: accept
                                 the proxy, drop everything else. Checked by `nft -c -f`.
  - sandbox-profile.resolved.yaml the manifest — absolute paths, uid, egress — for the
                                 Watchtower / audit reader.

Same emit/install split as govd_policy (T-2432): emit is agent-safe and runs nothing;
install is human/root only (Lock-1 Part 1) and bin/fw refuses it under the agent.

Two drift classes, both by CONTENT (sha256), never mtime (T-2290 lesson):
  stale  — source edited but `fw sandbox emit-profile` not re-run   (registry→generated class)
  drift  — emitted artefacts differ from the deployed copies        (emitted→installed class)

What this module deliberately does NOT emit: the active mediation tier (microVM +
virtio backends, gVisor fallback). The host has no VMM; a profile nothing can validate
is config with no check behind it. The tier goes on top of this floor when it lands.
"""
from __future__ import annotations

import hashlib
import os
import shutil
from pathlib import Path

import yaml

SOURCE_DEFAULT = "policy/sandbox-profile.yaml"
OUT_DIR_DEFAULT = "policy/sandbox-profile.d"
DEPLOYED_DEFAULT = os.environ.get("AEF_SANDBOX_DEPLOYED", "/etc/aef-sandbox")

UNIT_NAME = "aef-agent.service"
NFT_NAME = "aef-agent-egress.nft"
MANIFEST_NAME = "sandbox-profile.resolved.yaml"
ARTEFACTS = (UNIT_NAME, NFT_NAME, MANIFEST_NAME)

GENERATED_BANNER = "generated by `fw sandbox emit-profile` — DO NOT EDIT; edit policy/sandbox-profile.yaml and re-emit"


def sha256_file(path) -> str | None:
    p = Path(path)
    if not p.is_file():
        return None
    return hashlib.sha256(p.read_bytes()).hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------- source → resolved

def load_source(source) -> dict:
    p = Path(source)
    if not p.is_file():
        raise FileNotFoundError(f"sandbox profile source not found: {source}")
    data = yaml.safe_load(p.read_text()) or {}
    if data.get("version") != 1:
        raise ValueError(f"{source}: unsupported version {data.get('version')!r} (expected 1)")
    return data


def _abs(path: str, root: Path) -> str:
    p = Path(path)
    return str(p if p.is_absolute() else (root / p).resolve())


def resolve(source_data: dict, project_root) -> dict:
    """Turn the relative, sovereign-facing source into the absolute manifest the renders use.

    Validation is structural only: a path may not be both RO and RW, and inaccessible
    paths may not also be listed as readable. Existence is NOT required — trusted-state
    dirs are created by the *install* of T-2430/T-2432, which may not have happened yet;
    the unit prefixes those with `-` so systemd ignores a missing one.
    """
    root = Path(project_root).resolve()
    ro = sorted({_abs(p, root) for p in source_data.get("read_only", [])})
    rw = sorted({_abs(p, root) for p in source_data.get("read_write", [])})
    inacc = sorted({_abs(p, root) for p in source_data.get("inaccessible", [])})
    both = set(ro) & set(rw)
    if both:
        raise ValueError(f"paths listed as both read_only and read_write: {sorted(both)}")
    leak = set(inacc) & (set(ro) | set(rw))
    if leak:
        raise ValueError(f"inaccessible paths also listed as readable: {sorted(leak)}")
    uid = int(source_data.get("agent_uid", 0))
    if uid <= 0:
        raise ValueError("agent_uid must be a positive integer — uid 0 is the hole the cage closes")
    egress = source_data.get("egress") or {}
    extra = []
    for row in egress.get("extra_allow") or []:
        extra.append({"host": str(row["host"]), "port": int(row["port"]), "why": str(row.get("why", ""))})
    return {
        "version": 1,
        "project_root": str(root),
        "agent_user": str(source_data.get("agent_user", "aef-agent")),
        "agent_uid": uid,
        "read_write": rw,
        "read_only": ro,
        "inaccessible": inacc,
        "egress": {
            "proxy_host": str(egress.get("proxy_host", "127.0.0.1")),
            "proxy_port": int(egress.get("proxy_port", 4000)),
            "extra_allow": extra,
        },
        "deployed_dir": str(source_data.get("deployed_dir", DEPLOYED_DEFAULT)),
    }


# ---------------------------------------------------------------- renders (deterministic)

def _unit_path_list(paths, ignore_missing_outside: str) -> str:
    # Paths outside the working tree may not exist until their own install ran;
    # `-` tells systemd to skip a missing one instead of failing the unit.
    out = []
    for p in paths:
        out.append(p if p.startswith(ignore_missing_outside) else f"-{p}")
    return " ".join(out)


def render_unit(r: dict) -> str:
    root = r["project_root"]
    proxy = f"http://{r['egress']['proxy_host']}:{r['egress']['proxy_port']}"
    return f"""\
# {GENERATED_BANNER}
# Static floor of the OS cage (arc-013 T-2433, design §7a). The active mediation
# tier (microVM / gVisor) is layered on top of this unit, not replaced by it.
[Unit]
Description=AEF agent session — OS cage static floor
Documentation=file://{root}/docs/reports/T-2428-payload-mediation-design.md
After=network-online.target

[Service]
Type=simple
# S5 — uid demotion. The agent runs as root today; this line is the boundary.
User={r['agent_user']}
Group={r['agent_user']}
WorkingDirectory={root}
StateDirectory=aef-agent
Environment=HOME=/var/lib/aef-agent
Environment=CLAUDECODE=1
# the harness reaches the model only through the proxy (S3, mirrored in nftables)
Environment=ANTHROPIC_BASE_URL={proxy}
# operator substitutes the real launch line at install; env keeps the unit verifiable
ExecStart=/usr/bin/env claude-fw --termlink
UMask=0027
NoNewPrivileges=yes

# S4 — filesystem partition. Whole FS read-only, working tree writable, governance
# substrate inside the working tree read-only again (inner entry wins — pinned live
# on systemd 255). Absolute trusted-state paths carry `-`: skip if not installed yet.
ProtectSystem=strict
ProtectHome=yes
PrivateTmp=yes
ReadWritePaths={_unit_path_list(r['read_write'], root)}
ReadOnlyPaths={_unit_path_list(r['read_only'], root)}
InaccessiblePaths={_unit_path_list(r['inaccessible'], root)}

# S3 — cgroup-level mirror of the nftables floor: loopback only. Port pinning to
# the proxy is the nftables ruleset's job (IPAddressAllow= has no port axis).
IPAddressDeny=any
IPAddressAllow=localhost
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6

# hardening that does not touch namespaces — T-1660's mid-session userns failure
# is the class we must not re-create; the cage is entered at exec, not mid-session.
LockPersonality=yes
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
ProtectClock=yes
SystemCallArchitectures=native

[Install]
WantedBy=multi-user.target
"""


def _nft_addr_family(host: str) -> str:
    return "ip6" if ":" in host else "ip"


def render_nft(r: dict) -> str:
    eg = r["egress"]
    fam = _nft_addr_family(eg["proxy_host"])
    extra_lines = []
    for row in eg["extra_allow"]:
        why = f"  # {row['why']}" if row["why"] else ""
        extra_lines.append(
            f"    {_nft_addr_family(row['host'])} daddr {row['host']} tcp dport {row['port']} accept{why}")
    extra = ("\n" + "\n".join(extra_lines)) if extra_lines else ""
    return f"""\
#!/usr/sbin/nft -f
# {GENERATED_BANNER}
# S3 egress pin (arc-013 T-2433, design §7a): from the agent uid, the ONLY route out
# is the proxy. Everything else is counted, logged and dropped at the OUTPUT hook.
# The uid is numeric on purpose: nft resolves user names at parse time, and the
# ruleset must check clean (`nft -c -f`) before the user exists.
define aef_agent_uid = {r['agent_uid']}
define proxy_addr = {eg['proxy_host']}
define proxy_port = {eg['proxy_port']}

table inet aef_sandbox {{
    chain output {{
        type filter hook output priority filter; policy accept;
        meta skuid $aef_agent_uid jump aef_agent_egress
    }}

    chain aef_agent_egress {{
        {fam} daddr $proxy_addr tcp dport $proxy_port accept{extra}
        counter log prefix "aef-sandbox drop: " drop
    }}
}}
"""


def render_manifest(r: dict) -> str:
    head = f"# {GENERATED_BANNER}\n"
    return head + yaml.safe_dump(r, sort_keys=True, default_flow_style=False)


def render_all(r: dict) -> dict:
    return {UNIT_NAME: render_unit(r), NFT_NAME: render_nft(r), MANIFEST_NAME: render_manifest(r)}


# ---------------------------------------------------------------- emit / status / install

def emit_profile(source, project_root, out_dir) -> dict:
    """Render the three artefacts into OUT_DIR (agent-safe: writes repo files, runs nothing).
    Returns {artefact: sha256}."""
    r = resolve(load_source(source), project_root)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written = {}
    for name, text in render_all(r).items():
        (out / name).write_text(text)
        written[name] = sha256_text(text)
    return written


def stale_status(source, project_root, out_dir) -> dict:
    """Source edited but not re-emitted? Compares a fresh render against the on-disk
    artefacts. States: absent_source, absent_emitted, stale, ok."""
    try:
        r = resolve(load_source(source), project_root)
    except FileNotFoundError:
        return {"state": "absent_source", "differs": []}
    fresh = {name: sha256_text(text) for name, text in render_all(r).items()}
    on_disk = {name: sha256_file(Path(out_dir) / name) for name in ARTEFACTS}
    if all(v is None for v in on_disk.values()):
        return {"state": "absent_emitted", "differs": list(ARTEFACTS)}
    differs = [n for n in ARTEFACTS if on_disk[n] != fresh[n]]
    return {"state": "stale" if differs else "ok", "differs": differs}


def drift_status(out_dir, deployed_dir=DEPLOYED_DEFAULT) -> dict:
    """Emitted but not installed? Compares each emitted artefact against its deployed copy.
    States: absent_emitted, not_installed, drift, ok."""
    emitted = {n: sha256_file(Path(out_dir) / n) for n in ARTEFACTS}
    if all(v is None for v in emitted.values()):
        return {"state": "absent_emitted", "differs": list(ARTEFACTS)}
    deployed = {n: sha256_file(Path(deployed_dir) / n) for n in ARTEFACTS}
    if all(v is None for v in deployed.values()):
        return {"state": "not_installed", "differs": list(ARTEFACTS)}
    differs = [n for n in ARTEFACTS if emitted[n] != deployed[n]]
    return {"state": "drift" if differs else "ok", "differs": differs}


def status(source, project_root, out_dir, deployed_dir=DEPLOYED_DEFAULT) -> dict:
    """Combined verdict. Precedence: absent_source > absent_emitted > stale > not_installed
    > drift > ok — a stale emit is reported before install drift because re-emitting
    changes what install would deploy."""
    s = stale_status(source, project_root, out_dir)
    if s["state"] in ("absent_source", "absent_emitted", "stale"):
        return {"state": s["state"], "differs": s["differs"], "leg": "emit"}
    d = drift_status(out_dir, deployed_dir)
    return {"state": d["state"], "differs": d["differs"], "leg": "install"}


STATUS_EXIT = {"ok": 0, "not_installed": 0, "stale": 1, "drift": 1, "absent_emitted": 2, "absent_source": 2}

STATUS_LABEL = {
    "ok": "OK  sandbox profile emitted and deployed copies match",
    "not_installed": "SKIP  sandbox profile emitted but not installed (run: sudo fw sandbox install)",
    "stale": "WARN  sandbox-profile.yaml edited but not re-emitted (run: fw sandbox emit-profile)",
    "drift": "WARN  sandbox profile emitted but deployed copy differs (run: sudo fw sandbox install)",
    "absent_emitted": "ABSENT  no emitted profile yet (run: fw sandbox emit-profile)",
    "absent_source": "ERROR  policy/sandbox-profile.yaml missing",
}


def emit_install_spec(r: dict, out_dir, deployed_dir=DEPLOYED_DEFAULT) -> str:
    """EMIT ONLY. The human/root runs this; the agent prints it (Lock-1 Part 1)."""
    out = str(Path(out_dir).resolve())
    return f"""\
# ── sandbox profile install spec (EMIT ONLY — run yourself; the agent must NOT) ──
# Emitted (in-repo, reviewable):   {out}/
# Deployed (RO to the agent uid):  {deployed_dir}/
#
# 0. review the three artefacts, then check them the way install will:
systemd-analyze verify {out}/{UNIT_NAME}
nft -c -f {out}/{NFT_NAME}
# 1. the agent uid (S5) — fixed number so the nftables skuid match is stable:
sudo useradd --system --uid {r['agent_uid']} --shell /usr/sbin/nologin --home-dir /var/lib/aef-agent {r['agent_user']}
# 2. deploy the artefacts RO (idempotent; refuses under the agent):
sudo fw sandbox install
# 3. activate the egress floor (S3) and the unit (S4/S5):
sudo nft -f {deployed_dir}/{NFT_NAME}
sudo install -m 0644 {deployed_dir}/{UNIT_NAME} /etc/systemd/system/{UNIT_NAME} && sudo systemctl daemon-reload
# 4. confirm no drift, then the deciding validation (design §7a "build-check"):
fw sandbox status                 # expect: OK
sudo systemctl start {UNIT_NAME} && journalctl -u {UNIT_NAME} -n 50
#
# Drift contract: after ANY sovereign edit to policy/sandbox-profile.yaml, re-run
# `fw sandbox emit-profile` (stale class) and then steps 2-3 (drift class). Until then
# `fw sandbox status`, `fw doctor` and `fw audit` report the gap.
"""


def install_profile(out_dir, deployed_dir=DEPLOYED_DEFAULT) -> dict:
    """Copy emitted artefacts → DEPLOYED_DIR (root-only; bin/fw refuses this under the agent).
    Deploys files only — user creation, nft load and systemctl are the spec's steps 1/3,
    kept as explicit human actions so the deploy is reviewable line by line."""
    src = Path(out_dir)
    missing = [n for n in ARTEFACTS if not (src / n).is_file()]
    if missing:
        raise FileNotFoundError(f"emitted artefacts missing (run fw sandbox emit-profile): {missing}")
    dst = Path(deployed_dir)
    dst.mkdir(parents=True, exist_ok=True)
    installed = {}
    for n in ARTEFACTS:
        shutil.copy2(src / n, dst / n)
        os.chmod(dst / n, 0o644)
        installed[n] = sha256_file(dst / n)
    return {"deployed_dir": str(dst), "installed": installed}


def _main(argv) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog="govd_sandbox")
    ap.add_argument("action", choices=["emit-profile", "status", "spec", "install"])
    ap.add_argument("--source", default=os.environ.get("AEF_SANDBOX_PROFILE", SOURCE_DEFAULT))
    ap.add_argument("--project-root", default=os.environ.get("PROJECT_ROOT", "."))
    ap.add_argument("--out", default=None, help=f"emitted artefact dir (default: <project-root>/{OUT_DIR_DEFAULT})")
    ap.add_argument("--deployed", default=DEPLOYED_DEFAULT)
    args = ap.parse_args(argv[1:])
    out_dir = Path(args.out) if args.out else Path(args.project_root) / OUT_DIR_DEFAULT

    if args.action == "emit-profile":
        written = emit_profile(args.source, args.project_root, out_dir)
        for n, sha in written.items():
            print(f"emitted {out_dir / n} (sha256 {sha[:12]}…)")
        print()
        print(emit_install_spec(resolve(load_source(args.source), args.project_root), out_dir, args.deployed))
        return 0
    if args.action == "spec":
        print(emit_install_spec(resolve(load_source(args.source), args.project_root), out_dir, args.deployed))
        return 0
    if args.action == "status":
        s = status(args.source, args.project_root, out_dir, args.deployed)
        tail = f"  [{', '.join(s['differs'])}]" if s["differs"] and s["state"] not in ("ok", "not_installed") else ""
        print(f"{STATUS_LABEL[s['state']]}{tail}")
        return STATUS_EXIT[s["state"]]
    if args.action == "install":
        r = install_profile(out_dir, args.deployed)
        for n, sha in r["installed"].items():
            print(f"installed {Path(r['deployed_dir']) / n} (sha256 {sha[:12]}…)")
        return 0
    return 2


if __name__ == "__main__":
    import sys
    raise SystemExit(_main(sys.argv))
