#!/usr/bin/env python3
"""T-671: derive component-fabric edges for the Arc-0 component set from file content.

Edges are EXTRACTED, not asserted. For every member of the Arc-0 set this scans the
file's own bytes for references to other tracked repo paths and emits the pairs it
finds. A card written from this output can be traced back to a line in the source;
a card written by hand cannot.

Two reference forms are recognised:

  literal-path   a tracked repo path appearing verbatim in the text
                 (`tools/validate-workflow.py`, `src/aef-workflow-designer.html`)
  py-import      `import x` / `from x import` resolved against tools/ and tests/

  unique-basename  a filename with its extension (`bpmn-cli.py`) when exactly ONE
                   tracked path ends in it — `_bpmn-claim-cli-verify.py` invokes the
                   CLI as `os.path.join(HERE, 'bpmn-cli.py')`, a real edge that a
                   full-path-only scan misses entirely.

Deliberately NOT recognised: extensionless or AMBIGUOUS basenames. `validate-workflow`
without its extension, or any basename that more than one tracked path ends in, would
manufacture edges the source does not carry — the same defect class as a hand-
maintained claim. Uniqueness is what removes the ambiguity, so it is required, not
assumed.

Output: TSV `source<TAB>target<TAB>kind` on stdout, one edge per line.
Exit 0 always when the scan completes; the caller decides what the edges mean.
"""
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SET_FILE = os.path.join(REPO, "docs", "research", "executable-workflow",
                        "arc-0-component-set.txt")

# Reference kinds by extension of the REFERRING file. A .sh that names a .py runs it;
# a .py that names a .bpmn reads it. Nothing here guesses at write intent.
KIND_BY_TARGET = {
    ".py": "calls",
    ".sh": "calls",
    ".mjs": "calls",
    ".html": "reads",
    ".bpmn": "reads",
    ".xml": "reads",
    ".yaml": "reads",
    ".json": "reads",
    ".md": "reads",
}


def tracked_paths():
    out = subprocess.run(["git", "-C", REPO, "ls-files"],
                         capture_output=True, text=True, check=True).stdout
    return set(out.splitlines())


def arc0_set():
    with open(SET_FILE) as fh:
        return [ln.strip() for ln in fh
                if ln.strip() and not ln.lstrip().startswith("#")]


def _live_lines(text, ext=".py"):
    """Text with comments removed, per the referring file's own language.

    MENTION IS NOT INVOCATION (T-669). tests/run-bridge-tests.sh names 156 tool paths,
    many in comments pointing at related probes. src/aef-workflow-designer.html names
    scripts/embed-fonts.py in an HTML comment ("Generated by ... do not hand-edit") and
    tests/test_editor_bridge_meta_parity.py in a `//` comment. Cards built from those
    would assert that the product CALLS its own generator and its own test — one of
    them backwards in direction. A path earns an edge only outside a comment.

    THE STRIPPER MUST FOLLOW THE LANGUAGE. Stripping only `#` was correct for .py/.sh
    and silently inert on .html/.mjs, so the false edges appeared exactly where the
    stripper did not apply — the defect hid one language over from where it was fixed.

    Deliberately crude within each language (no string-literal awareness): over-
    stripping can only ever DROP a candidate edge, never invent one. Under-claiming an
    edge is a visible hole; over-claiming is a false record.
    """
    if ext in (".mjs", ".html"):
        text = re.sub(r"<!--.*?-->", " ", text, flags=re.S)
        text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
        line_comment = "//"
    else:
        # Python module/def docstrings are self-description, not invocation: the
        # purpose text is sourced from them precisely because they DESCRIBE rather
        # than call. Blank them before scanning for edges.
        if ext == ".py":
            text = re.sub(r'"""(.*?)"""', " ", text, flags=re.S)
            text = re.sub(r"'''(.*?)'''", " ", text, flags=re.S)
        line_comment = "#"

    out = []
    for line in text.splitlines():
        s = line.split(line_comment, 1)[0]
        if s.strip():
            out.append(s)
    return "\n".join(out)


def unique_basenames(tracked):
    """basename -> path, only for basenames exactly one tracked path ends in."""
    seen = {}
    for p in tracked:
        b = os.path.basename(p)
        seen.setdefault(b, []).append(p)
    return {b: v[0] for b, v in seen.items() if len(v) == 1}


def literal_refs(text, tracked, self_path, uniq):
    """Tracked repo paths referenced outside comments in the file's own text."""
    found = set()
    live = _live_lines(text, os.path.splitext(self_path)[1])
    # Full paths: require at least one slash so an ambiguous bare name cannot match.
    for p in tracked:
        if p == self_path or "/" not in p:
            continue
        if not p.startswith(("src/", "tools/", "tests/", "scripts/", "docs/standards/")):
            continue
        if p in live:
            found.add(p)
    # Unique basenames: no ambiguity to guard against, so the slash is not required.
    for b, p in uniq.items():
        if p == self_path or p in found:
            continue
        if not p.startswith(("src/", "tools/", "tests/", "scripts/", "docs/standards/")):
            continue
        if re.search(r"(?<![\w./-])" + re.escape(b) + r"(?![\w-])", live):
            found.add(p)
    return found


def import_refs(text, tracked, self_path):
    """Python imports resolved against tools/ and tests/."""
    found = set()
    for m in re.finditer(r"^\s*(?:from|import)\s+([A-Za-z_][\w]*)", text, re.M):
        mod = m.group(1)
        for d in ("tools", "tests"):
            cand = f"{d}/{mod}.py"
            if cand in tracked and cand != self_path:
                found.add(cand)
    return found


def literal_refs_reverse(live, members, uniq):
    """Which Arc-0 members this already-comment-stripped text references."""
    hits = set()
    for m in members:
        if m in live:
            hits.add(m)
            continue
        b = os.path.basename(m)
        if uniq.get(b) == m and re.search(
                r"(?<![\w./-])" + re.escape(b) + r"(?![\w-])", live):
            hits.add(m)
    return hits


def main():
    tracked = tracked_paths()
    uniq = unique_basenames(tracked)
    members = arc0_set()
    missing = [m for m in members if not os.path.exists(os.path.join(REPO, m))]
    if missing:
        sys.stderr.write("REFUSE: set members do not exist: %s\n" % ", ".join(missing))
        return 2

    # FORWARD: what each member depends on.
    edges = []
    for m in members:
        with open(os.path.join(REPO, m), encoding="utf-8", errors="replace") as fh:
            text = fh.read()
        refs = literal_refs(text, tracked, m, uniq) | import_refs(text, tracked, m)
        for r in sorted(refs):
            kind = KIND_BY_TARGET.get(os.path.splitext(r)[1], "reads")
            edges.append((m, r, kind))

    # REVERSE: who depends on each member. Scanning only the 28 members against each
    # other would yield a graph closed under its own scope — every card would look
    # self-contained because the things that actually call it were out of frame. The
    # reverse pass ranges over every tracked code file so `depended_by` reports real
    # inbound edges from outside the Arc-0 set.
    member_set = set(members)
    scan = [p for p in sorted(tracked)
            if p.startswith(("src/", "tools/", "tests/", "scripts/"))
            and os.path.splitext(p)[1] in (".py", ".sh", ".mjs", ".html")]
    rev = []
    for p in scan:
        if p in member_set:
            continue  # forward pass already covered member→member
        fp = os.path.join(REPO, p)
        if not os.path.exists(fp):
            continue
        with open(fp, encoding="utf-8", errors="replace") as fh:
            live = _live_lines(fh.read(), os.path.splitext(p)[1])
        hits = literal_refs_reverse(live, members, uniq)
        for m in sorted(hits):
            kind = KIND_BY_TARGET.get(os.path.splitext(m)[1], "reads")
            rev.append((p, m, kind))

    for s, t, k in edges + rev:
        print(f"{s}\t{t}\t{k}")
    sys.stderr.write(
        f"scanned {len(members)} member(s) forward + {len(scan)} file(s) reverse; "
        f"derived {len(edges)} forward + {len(rev)} inbound edge(s)\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
