#!/usr/bin/env python3
"""_t682-boundary-inventory.py — derive the editor's reachable authority surface.

WHY DERIVED AND NOT HAND-LISTED
-------------------------------
A boundary document that is typed by hand is accurate exactly once. This derives
the route set from `gallery-serve.py`'s own dispatch via AST, so a route added
later cannot quietly stay out of the inventory: the drift check goes red.

WHAT AN ABSENCE ROW MEANS
-------------------------
Arc 2 names three authorities — mutation, execution, secret. Only mutation is
reachable here. The other two get rows that say ABSENT, carrying the patterns
searched and the line numbers found, because an empty row in a security document
reads like a control that passed. It is not. It is a place nobody looked, unless
the document says what was looked for.

Symmetrically, an absence must not be OVERCLAIMED. The task filing said execution
authority "does not exist in this tree at all". It does: one fixed-argument
`subprocess.check_output(['hostname', '-I'])` in the startup banner. It is
unreachable from any route and takes no request-derived input, which is a much
narrower and checkable claim than "does not exist" — so that is the claim made.

MODES
-----
  (default)     check the committed report against the derived surface -> exit 1 on drift
  --write       regenerate the report from source
  --self-test   prove the drift check goes red on an added route
"""
from __future__ import annotations

import argparse
import ast
import os
import re
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..'))
SERVER = os.path.join(HERE, 'gallery-serve.py')
REPORT = os.path.join(REPO, 'docs', 'reports', 'T-682-arc-2-boundary-inventory.md')

# Authority classes Arc 2 names. Each maps to the patterns that would evidence it.
EXECUTION_PATTERNS = [r'subprocess', r'os\.system', r'os\.popen', r'\bexec\(', r'\beval\(',
                      r'Popen', r'os\.spawn', r'commands\.']
SECRET_PATTERNS = [r'secret', r'password', r'passwd', r'token', r'credential',
                   r'api_key', r'apikey', r'private_key']

# What each mutation route touches, and which fence covers it. Hand-authored
# semantics; the ROUTE SET itself is derived, so a new route lands unclassified
# and the check fails rather than silently inheriting a neighbour's row.
ROUTE_SEMANTICS = {
    ('GET', '/api/health'):   ('none — liveness only', 'n/a (no path derived from input)'),
    ('GET', '/api/list'):     ('none — enumerates corpus + saved maps', 'n/a (no id accepted)'),
    ('GET', '/api/versions'): ('none — reads index.json', 'ID_RE only (read path)'),
    ('GET', '/api/version'):  ('none — reads vN.bpmn', 'ID_RE only (read path)'),
    ('GET', '/api/thumb'):    ('none — reads vN.png', 'ID_RE only (read path)'),
    ('POST', '/api/save'):    ('WRITES 5 targets: vN.bpmn, vN.png, index.json, corpus copy, served copy',
                               'T-683 per-target containment (_escaping_save_target)'),
    ('POST', '/api/delete'):  ('MOVES sources to .editor-versions/_trash/',
                               '_within_repo via archive_move (delete path)'),
}


def derive_routes(src: str) -> set[tuple[str, str]]:
    """Route set from the dispatch itself: GET literals in _api_get, POST allowlist in do_POST."""
    tree = ast.parse(src)
    routes: set[tuple[str, str]] = set()

    def api_literals(node) -> set[str]:
        out = set()
        for n in ast.walk(node):
            if isinstance(n, ast.Constant) and isinstance(n.value, str) \
                    and n.value.startswith('/api/'):
                out.add(n.value)
        return out

    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == '_api_get':
            routes |= {('GET', p) for p in api_literals(node)}
        elif isinstance(node, ast.FunctionDef) and node.name == 'do_POST':
            routes |= {('POST', p) for p in api_literals(node)}
    return routes


def scan(src: str, patterns: list[str]) -> list[tuple[int, str]]:
    """Line numbers matching any pattern — the evidence behind an absence claim."""
    hits = []
    for i, line in enumerate(src.splitlines(), 1):
        for p in patterns:
            if re.search(p, line, re.I):
                hits.append((i, line.strip()))
                break
    return hits


def render(routes: set[tuple[str, str]], src: str) -> str:
    execution = scan(src, EXECUTION_PATTERNS)
    secret = scan(src, SECRET_PATTERNS)

    lines = [
        '# T-682 — Arc-2 boundary inventory: the editor\'s reachable authority surface',
        '',
        '**Generated by `tools/_t682-boundary-inventory.py` — do not hand-edit.**',
        'The route table is derived from `tools/gallery-serve.py`\'s own dispatch via AST.',
        'A route added to the server without a row here fails the drift check.',
        '',
        '## 1. Mutation authority — the reachable surface',
        '',
        '| method | path | what it mutates | containment |',
        '|---|---|---|---|',
    ]
    for method, path in sorted(routes):
        mutates, fence = ROUTE_SEMANTICS.get((method, path), ('UNCLASSIFIED', 'UNCLASSIFIED'))
        lines.append('| %s | `%s` | %s | %s |' % (method, path, mutates, fence))

    lines += [
        '',
        'Seven routes, matching the S1 (T-681) measurement. Two of them mutate; the other',
        'five are read paths fenced by `ID_RE` alone, which is adequate because they resolve',
        'a path for READING and a failed resolution is a 404, not a write outside the store.',
        '',
        '## 2. Execution authority — ABSENT FROM THE REQUEST SURFACE (narrower than "absent")',
        '',
    ]
    if execution:
        lines.append('Patterns searched: `%s`' % '`, `'.join(EXECUTION_PATTERNS))
        lines.append('')
        lines.append('**%d match(es) found — so this is NOT a bare absence:**' % len(execution))
        lines.append('')
        for ln, text in execution:
            lines.append('- `gallery-serve.py:%d` — `%s`' % (ln, text))
        lines += [
            '',
            'The claim this document makes is therefore the narrow, checkable one: **no route',
            'reaches an execution primitive, and no execution primitive takes request-derived',
            'input.** The matches above sit in the startup banner with fixed argument vectors.',
            '',
            'The task filing said execution authority "does not exist in this tree at all".',
            'That was an overclaim. Overclaiming an absence is the same failure as mistaking',
            'one for a defence — both put a confident sentence where a measurement belongs.',
        ]
    else:
        lines += [
            'Patterns searched: `%s`' % '`, `'.join(EXECUTION_PATTERNS),
            '',
            '**Zero matches.** No execution primitive exists in this file.',
        ]

    lines += [
        '',
        '## 3. Secret authority — ABSENT',
        '',
        'Patterns searched: `%s`' % '`, `'.join(SECRET_PATTERNS),
        '',
    ]
    if secret:
        lines.append('**%d match(es) — absence claim does not hold:**' % len(secret))
        for ln, text in secret:
            lines.append('- `gallery-serve.py:%d` — `%s`' % (ln, text))
    else:
        lines += [
            '**Zero matches.** The editor holds, reads and transmits no secret of any kind.',
            '',
            'This row is empty because there is nothing there — not because nobody looked.',
            'The patterns above are what was looked for; that is the difference between an',
            'absence and a blind spot, and it is the reason this row exists at all rather',
            'than being omitted for having nothing to say.',
        ]

    lines += [
        '',
        '## 4. What this inventory does NOT claim',
        '',
        '- It does not claim the five read routes are unexploitable — only that they read.',
        '- It does not cover the static file handler inherited from `SimpleHTTPRequestHandler`',
        '  (`super().do_GET()` for non-`/api/` paths), which serves DOCROOT and is out of the',
        '  Arc-2 authority frame.',
        '- Absence rows are evidence of what was searched, not proof that no other shape of',
        '  the same authority exists under a name the patterns do not match.',
        '',
        '*Regenerate: `python3 tools/_t682-boundary-inventory.py --write`*',
        '',
    ]
    return '\n'.join(lines)


def parse_report_routes(text: str) -> set[tuple[str, str]]:
    out = set()
    for m in re.finditer(r'^\|\s*(GET|POST)\s*\|\s*`(/api/[^`]+)`\s*\|', text, re.M):
        out.add((m.group(1), m.group(2)))
    return out


def check(server_src: str | None = None) -> int:
    src = server_src if server_src is not None else open(SERVER, encoding='utf-8').read()
    derived = derive_routes(src)
    if not os.path.exists(REPORT):
        print('DRIFT: report does not exist — run --write', file=sys.stderr)
        return 1
    documented = parse_report_routes(open(REPORT, encoding='utf-8').read())

    missing = derived - documented
    extra = documented - derived
    unclassified = {r for r in derived if r not in ROUTE_SEMANTICS}

    if missing or extra or unclassified:
        print('DRIFT between the server and the boundary inventory:', file=sys.stderr)
        for r in sorted(missing):
            print('  IN SERVER, NOT DOCUMENTED: %s %s' % r, file=sys.stderr)
        for r in sorted(extra):
            print('  DOCUMENTED, NOT IN SERVER: %s %s' % r, file=sys.stderr)
        for r in sorted(unclassified):
            print('  UNCLASSIFIED (no semantics row): %s %s' % r, file=sys.stderr)
        print('\nA route the boundary document does not know about is a route nobody',
              file=sys.stderr)
        print('fenced on purpose. Run --write after adding its semantics.', file=sys.stderr)
        return 1

    print('OK — %d routes, server and inventory agree, all classified' % len(derived))
    return 0


def self_test() -> int:
    """The drift check must go red on an added route, or it is a claim not a control."""
    src = open(SERVER, encoding='utf-8').read()
    injected = src.replace(
        "        if route == '/api/health':",
        "        if route == '/api/exfiltrate':\n            return self._json(200, {})\n"
        "        if route == '/api/health':", 1)
    if injected == src:
        print('SELF-TEST FAIL: could not inject a route', file=sys.stderr)
        return 1
    derived = derive_routes(injected)
    if ('GET', '/api/exfiltrate') not in derived:
        print('SELF-TEST FAIL: the deriver did not see the injected route', file=sys.stderr)
        return 1
    code = check(server_src=injected)
    if code == 0:
        print('SELF-TEST FAIL: drift check stayed green with an extra route present',
              file=sys.stderr)
        return 1
    print('\nself-test OK — an added route makes the drift check go red')
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--write', action='store_true', help='regenerate the report from source')
    ap.add_argument('--self-test', action='store_true')
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    src = open(SERVER, encoding='utf-8').read()
    if args.write:
        os.makedirs(os.path.dirname(REPORT), exist_ok=True)
        with open(REPORT, 'w', encoding='utf-8') as f:
            f.write(render(derive_routes(src), src))
        print('wrote %s' % os.path.relpath(REPORT, REPO))
        return 0
    return check(src)


if __name__ == '__main__':
    sys.exit(main())
