#!/usr/bin/env python3
"""_t989-measure-evergreen.py — score a batch of BPMN maps the same way every iteration (T-989).

The Evergreen trial asks whether a vendor agent, given only the 0.15.0 authoring kit and its
review loop, produces better maps than their script did. "Better" is only measurable if every
batch is scored by the same instrument, so this file IS the definition of the trial's numbers.
Iteration 0 is their original corpus (26 maps, generated by a script).

Per map, and totalled:
  - validator findings by rule (the one validator, run_xml)
  - workflowMeta present, and its kind
  - lanes, lanes with a declared authority, authority values
  - start events, end events (a script invented one start/end per orphan step)
  - connected parts of the flow graph, and how many extra parts carry an order-unknown
    annotation (an associated textAnnotation): honest disconnection vs unexplained
  - element citations: <documentation> source "quote" / unstated / none (the kit's convention)

Usage: _t989-measure-evergreen.py <dir-with-.bpmn> [--label NAME] [--json OUT] [--baseline DIR]
--baseline: score DIR too and compare map by map, only over the maps both sets contain (key: as-is
or Soll + file name), so a partial batch is compared with the same maps, not the whole corpus.
Writes nothing unless --json is given. The corpus itself is never committed (owner approved
sending, not archiving); only the numbers go into docs/reports/T-989-evergreen-trial.md.
"""
import argparse
import collections
import glob
import importlib.util
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
FLOW = {'startEvent', 'endEvent', 'task', 'userTask', 'serviceTask', 'scriptTask', 'subProcess',
        'exclusiveGateway', 'parallelGateway', 'intermediateCatchEvent', 'intermediateThrowEvent',
        'boundaryEvent'}


def load_validator():
    spec = importlib.util.spec_from_file_location('_t989_v', os.path.join(HERE, 'validate-workflow.py'))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def local(tag):
    return tag.rsplit('}', 1)[-1]


def measure(path, val):
    text = open(path, encoding='utf-8').read()
    root = ET.fromstring(text)
    proc = next((e for e in root.iter() if local(e.tag) == 'process'), None)
    m = {'map': os.path.basename(path)}
    m['findings'] = dict(collections.Counter(f.rule for f in val.run_xml(text)))
    wm = next((e for e in root.iter() if local(e.tag) == 'workflowMeta'), None)
    m['workflowMeta'] = wm is not None
    m['kind'] = wm.get('kind') if wm is not None else None
    lanes = [e for e in root.iter() if local(e.tag) == 'lane']
    auth = [next((x.get('authority') for x in l.iter() if local(x.tag) == 'laneMeta'), None) for l in lanes]
    m['lanes'] = len(lanes)
    m['lanes_with_authority'] = sum(1 for a in auth if a)
    m['authorities'] = dict(collections.Counter(a or '(none declared)' for a in auth))
    nodes = {e.get('id'): local(e.tag) for e in (proc if proc is not None else []) if local(e.tag) in FLOW}
    m['flow_nodes'] = len(nodes)
    m['start_events'] = sum(1 for t in nodes.values() if t == 'startEvent')
    m['end_events'] = sum(1 for t in nodes.values() if t == 'endEvent')
    # connected parts (undirected) over sequence flows
    adj = {n: set() for n in nodes}
    for f in root.iter():
        if local(f.tag) == 'sequenceFlow':
            s, t = f.get('sourceRef'), f.get('targetRef')
            if s in adj and t in adj:
                adj[s].add(t); adj[t].add(s)
    seen, parts = set(), []
    for n in adj:
        if n in seen:
            continue
        stack, comp = [n], set()
        while stack:
            x = stack.pop()
            if x in comp:
                continue
            comp.add(x); stack.extend(adj[x] - comp)
        seen |= comp; parts.append(comp)
    # An extra part is "explained" when a note says why it is not connected. Two forms, counted
    # SEPARATELY so the trial can show a move from one to the other:
    #   association  the kit's form: a textAnnotation linked to the node by an <association>
    #   lane-note    Evergreen's iteration-0 form: a free textAnnotation whose id is
    #                '<laneId>_note', covering every node in that lane (no association at all)
    associated = set()
    for a in root.iter():
        if local(a.tag) == 'association':
            associated.add(a.get('targetRef')); associated.add(a.get('sourceRef'))
    lane_of = {}
    for l in lanes:
        for ref in l.iter():
            if local(ref.tag) == 'flowNodeRef' and ref.text:
                lane_of[ref.text.strip()] = l.get('id')
    noted_lanes = {e.get('id', '')[:-len('_note')] for e in root.iter()
                   if local(e.tag) == 'textAnnotation' and e.get('id', '').endswith('_note')}
    parts.sort(key=len, reverse=True)
    extra = parts[1:]
    m['parts'] = len(parts)
    m['extra_parts_by_association'] = sum(1 for p in extra if p & associated)
    m['extra_parts_by_lane_note'] = sum(1 for p in extra if not (p & associated)
                                        and any(lane_of.get(n) in noted_lanes for n in p))
    m['extra_parts_unexplained'] = (len(extra) - m['extra_parts_by_association']
                                    - m['extra_parts_by_lane_note'])
    # citations (kit convention)
    q = u = n_ = 0
    for e in root.iter():
        if local(e.tag) not in FLOW | {'lane'}:
            continue
        d = next((c.text or '' for c in e if local(c.tag) == 'documentation'), None)
        if d and re.search(r'source:\s*"', d):
            q += 1
        elif d and 'unstated' in d:
            u += 1
        else:
            n_ += 1
    m['cited_quote'], m['cited_unstated'], m['uncited'] = q, u, n_
    return m


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument('dir')
    ap.add_argument('--label', default='batch')
    ap.add_argument('--json')
    ap.add_argument('--baseline')
    a = ap.parse_args(argv)
    files = sorted(glob.glob(os.path.join(a.dir, '**', '*.bpmn'), recursive=True))
    if not files:
        print('COULD-NOT-MEASURE: no .bpmn under %s' % a.dir, file=sys.stderr)
        return 3
    val = load_validator()
    rows = [measure(f, val) for f in files]
    tot = collections.Counter()
    rules = collections.Counter()
    for r in rows:
        for k in ('lanes', 'lanes_with_authority', 'flow_nodes', 'start_events', 'end_events',
                  'extra_parts_by_association', 'extra_parts_by_lane_note', 'extra_parts_unexplained', 'cited_quote',
                  'cited_unstated', 'uncited'):
            tot[k] += r[k]
        tot['maps_with_workflowMeta'] += r['workflowMeta']
        tot['maps_with_kind'] += bool(r['kind'])
        tot['maps_multi_start'] += r['start_events'] > 1
        rules.update(r['findings'])
    summary = {'label': a.label, 'maps': len(rows), 'totals': dict(tot),
               'findings_by_rule': dict(rules.most_common()), 'findings_total': sum(rules.values())}
    print(json.dumps(summary, indent=1))
    if a.json:
        json.dump({'summary': summary, 'maps': rows}, open(a.json, 'w'), indent=1)
    if a.baseline:
        compare(a.baseline, files, rows, val)
    return 0


def key(path):
    # as-is and Soll share file names (the iteration-0 collision): the set is part of the key
    return ('soll' if 'soll' in path.lower() else 'as-is', os.path.basename(path))


COLS = (('findings', lambda r: sum(r['findings'].values())), ('lanes_auth', lambda r: '%d/%d' % (r['lanes_with_authority'], r['lanes'])),
        ('meta', lambda r: int(r['workflowMeta'])), ('start/end', lambda r: '%d/%d' % (r['start_events'], r['end_events'])),
        ('unexpl', lambda r: r['extra_parts_unexplained']), ('quote/unst/none', lambda r: '%d/%d/%d' % (r['cited_quote'], r['cited_unstated'], r['uncited'])))


def compare(base_dir, files, rows, val):
    bfiles = sorted(glob.glob(os.path.join(base_dir, '**', '*.bpmn'), recursive=True))
    base = {key(f): measure(f, val) for f in bfiles}
    new = {key(f): r for f, r in zip(files, rows)}
    both = sorted(set(base) & set(new))
    print('\nPAIRED with %s: %d map(s) in both; %d new-only %s; baseline has %d' % (
        base_dir, len(both), len(set(new) - set(base)), sorted('/'.join(k) for k in set(new) - set(base)), len(base)))
    print('%-46s ' % 'map' + ' '.join('%-16s' % c for c, _ in COLS))
    tb = tn = 0
    for k in both:
        b, n = base[k], new[k]
        tb += sum(b['findings'].values()); tn += sum(n['findings'].values())
        print('%-46s ' % '/'.join(k)[:46] + ' '.join('%-16s' % ('%s -> %s' % (f(b), f(n))) for _, f in COLS))
    if both:
        print('findings over the paired maps: %d -> %d' % (tb, tn))


if __name__ == '__main__':
    sys.exit(main())
